services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PORT=8000
    restart: always
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

